add brainstorming meeting 2 notes and related spec files
cse110-sp24-group12/cse110-sp24-group12 pull request #19
Opened 2024-05-05 22:49 UTC by sadsoap

## Tracking Info

Resolves #18 

## Changes

added brainstorming meeting 2 notes and related spec files

## Testing

N/A
## Confirmation of Change

Added brainstorm meeting notes from 05/03 to admin/meetings, and added the updated feature mindmap and user stories to specs/brainstorm.

2024-05-05 22:53 UTC, RamtinTJB requested changes
Great work! Just fix the extension for the markdown file and we are good to go

2024-05-05 22:53 UTC, RamtinTJB commented on admin/meetings/050324-brainstorm
Make sure the file extension is .md for markdown

2024-05-05 22:56 UTC, RamtinTJB approved these changes
Thanks!

2024-05-05 22:56 UTC, merged

2024-05-06 00:09 UTC, lindseyrapp commented
Thanks for doing this!