Password page
cse110-sp24-group12/cse110-sp24-group12 pull request #63
Opened 2024-05-22 21:18 UTC by matt0923

## Tracking Info

Resolves issue #43

## Changes

We added functionality to the password page part of the website, including:
. A main page for entering the password
. A create password page
. A create pin page
. A help page
. A "remember me" option. 

## Testing

No testing yet, just visually made sure that the feature covered all aspects of the issue and worked as it was intended to (testing will come in the next few days). 

## Confirmation of Change

![image](https://github.com/cse110-sp24-group12/cse110-sp24-group12/assets/74699880/33527eb7-a5d1-405b-b79d-d42db7a6b408)

2024-05-22 21:28 UTC, lindseyrapp submitted a review, later dismissed
This is great progress, thanks so much guys. It's looking great, the styling is awesome. A couple things to keep in mind, we want to make sure that we are redirected back to the password page after creating a new password & pin. Additionally, we want the password/pin fields to contain the new created password/pin after entered. So far, so good, these are just some next steps. 
Partially resolves #63 (still needs some changes but great progress!)

2024-05-22 21:48 UTC, lindseyrapp commented
It looks like there are some issues in your code that are not passing the Lint check. I resolved the one in preload.js but there are others in main & some other files you may want to check out.

2024-05-24 05:41 UTC, RamtinTJB requested changes
Great job on this guys! I just left a few comments once these are resolved we can go ahead and merge. Also please make sure to add JSDoc documentation to all the functions and any piece of code that handles logic.

2024-05-24 05:41 UTC, RamtinTJB commented on source/main.js
> +
Make sure to add proper JSDoc documentation to these methods. Refer to the ones right above this to see examples

2024-05-24 05:41 UTC, RamtinTJB commented on source/password.html
> +                    <div id="myModal" class="modal">
Thanks for adding a help popup! Just make sure that the background is opaque and the text is readable on different screen sizes (at least different desktop sizes, don't worry about readability on mobile and tablet for now)

2024-05-24 05:41 UTC, RamtinTJB commented on source/scripts/createPassword.js
> +        if (input.value.length < 6) {
Does this mean that the pin can only be less than 6 characters long? Do you guys think we can have a variable that keeps track of whether the user is entering the pin or the password and then check that variable in this if statement instead?

2024-05-25 18:46 UTC, RamtinTJB approved these changes
Great work guys! Thank you for writing the documentation and addressing the comments!

2024-05-25 18:47 UTC, merged