44 dashboard edit in js and css file to include more days and more activeness modes
cse110-sp24-group12/cse110-sp24-group12 pull request #73
Opened 2024-05-24 22:48 UTC by sidhantsinghvi

## Tracking Info

Resolves #<issue number>

## Changes

## Testing

## Confirmation of Change

2024-05-25 19:03 UTC, RamtinTJB requested changes
Great work on this! I left some comments, after addressing these we can go ahead and merge. I also noticed that all the sizes are hard coded and so the dashboard page won't work on different screen sizes. If you also address this in this pull request it would be great. If not we can make another issue for it for next week. (By different screen sizes I mean different laptop screen sizes. We don't need to support mobile screens since this is a desktop application)

2024-05-25 19:03 UTC, RamtinTJB commented on .vscode/settings.json
Please remove this file the pull request. This file is a vscode settings file and it should only be on your local machine. After deleting it and committing, you can add also add `.vscode/settings.json` in the `.gitignore` file so that this won't happen again

2024-05-25 19:03 UTC, RamtinTJB commented on source/scripts/dashboard.js
> +console.log('Dashboard script loaded');
please remove all the `console.log` calls in this file

2024-05-25 19:03 UTC, RamtinTJB commented on source/scripts/dashboard.js
> +//          console.log('Reading JSON file:', jsonPath);
Please remove all the commented out code from this file. This code will still be in the commit history if we wanted to reference it in the future.

2024-05-26 21:18 UTC, RamtinTJB approved these changes
Nice job! thanks for making the changes

2024-05-26 21:19 UTC, merged

2024-05-27 22:15 UTC, lindseyrapp commented
This looks great! Thanks guys! Awesome progress.